image: node:10

stages:
  - test

check:
  image: docker-registry.linagora.com:5000/linshare-snapshots/linshare-build-helper:latest
  stage: test
  tags:
      - docker
  script:
    - check_author.py check "${GITLAB_USER_EMAIL}" "${GITLAB_USER_NAME}" --no-accents

test:
  stage: test
  except:
    - triggers
  tags:
    - docker
  image: node:10
  script:
   - npm install
   - npm run test:unit
